/**
 * generated by Xtext 2.13.0
 */
package org.example.smalljava.ide;

import org.example.smalljava.ide.AbstractSmallJavaIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SmallJavaIdeModule extends AbstractSmallJavaIdeModule {
}
