/*
 * generated by Xtext 2.13.0
 */
package org.example.smalljava.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.example.smalljava.ui.internal.SmalljavaActivator;

public class SmallJavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmalljavaActivator.getInstance().getInjector("org.example.smalljava.SmallJava");
	}

}
