/**
 * generated by Xtext 2.13.0
 */
package org.example.expressions.validation;

import org.example.expressions.validation.AbstractExpressionsValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ExpressionsValidator extends AbstractExpressionsValidator {
}
