/**
 * generated by Xtext 2.13.0
 */
package org.example.smalljava.scoping;

import org.example.smalljava.scoping.AbstractSmallJavaScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SmallJavaScopeProvider extends AbstractSmallJavaScopeProvider {
}
