/*
 * generated by Xtext 2.13.0
 */
package org.example.expressions.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.example.expressions.expressions.ExpressionsModel
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import static extension org.junit.Assert.*
import org.example.expressions.expressions.VariableRef

@RunWith(XtextRunner)
@InjectWith(ExpressionsInjectorProvider)
class ExpressionsParsingTest {

	@Inject extension ParseHelper<ExpressionsModel>

	@Test def void testEvalExpression() {
		"eval 10".parse.assertNotNull
	}

	@Test def void testVariable() {
		"var i = 10".parse.assertNotNull
	}

	@Test def void testVariableReference() {

		'''
			var i = 10
			eval i
		'''.parse => [
			(elements.last.expression as VariableRef).variable.assertSame(elements.head)
		]
	}
}
