/*
 * generated by Xtext 2.13.0
 */
package org.example.expressions.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.example.expressions.expressions.BoolConstant
import org.example.expressions.expressions.Expression
import org.example.expressions.expressions.ExpressionsModel
import org.example.expressions.expressions.IntConstant
import org.example.expressions.expressions.Minus
import org.example.expressions.expressions.Plus
import org.example.expressions.expressions.StringConstant
import org.example.expressions.expressions.VariableRef
import org.junit.Test
import org.junit.runner.RunWith

import static extension org.junit.Assert.*

@RunWith(XtextRunner)
@InjectWith(ExpressionsInjectorProvider)
class ExpressionsParsingTest {

	@Inject extension ParseHelper<ExpressionsModel>

	@Test def void testEvalExpression() {
		"eval 10".parse.assertNotNull
	}

	@Test def void testVariable() {
		"var i = 10".parse.assertNotNull
	}

	@Test def void testEvalBooleanConstant() {
		"eval true".parse.assertNotNull
	}

	@Test def void testEvalStringConstant() {
		'eval "a string"'.parse.assertNotNull
	}

	@Test def void testVariableReference() {

		'''
			var i = 10
			eval i
		'''.parse => [
			(elements.last.expression as VariableRef).variable.assertSame(elements.head)
		]
	}

	def private String stringRepr(Expression e) {
		switch (e) {
			Plus: '''(«e.left.stringRepr» + «e.right.stringRepr»)'''
			Minus: '''(«e.left.stringRepr» - «e.right.stringRepr»)'''
			IntConstant: '''«e.value»'''
			StringConstant: '''«e.value»'''
			BoolConstant: '''«e.value»'''
			VariableRef: '''«e.variable.name»'''
		}.toString
	}

	def private assertRepr(CharSequence input, CharSequence expected) {
		("eval " + input).parse => [expected.assertEquals(elements.last.expression.stringRepr)]
	}

	@Test def void testPlus() {
		"10 + 5 + 1 + 2".assertRepr("(((10 + 5) + 1) + 2)")
	}

	@Test def void testParenthesis() {
		10.assertEquals(("eval (10)".parse.elements.head.expression as IntConstant).value)
	}

	@Test def void testPlusWithParenthesis() {
		"( 10 + 5 ) + ( 1 +2)".assertRepr("((10 + 5) + (1 + 2))")
	}

	@Test def void testMinus() {
		"1-2-3".assertRepr("((1 - 2) - 3)")
	}

	@Test def void testMinusWithParenthesis() {
		"1-(19-4)".assertRepr("(1 - (19 - 4))")
	}

	@Test def void test_minus_and_plus() {
		"1-4+9".assertRepr("((1 - 4) + 9)")
	}

	@Test def void test_m_and_p_with_parenthesis() {
		"1+(5-9)".assertRepr("(1 + (5 - 9))")
	}

	@Test def void bla() {
		"true + 'treu'".assertRepr("(true + treu)")
	}
}
